name = "MinePack Vanilla 2 Plus"
author = "yarinka-yyy"
version = "0.19.8"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d9bbd447d1ac4c910429fb64d7892aba01b9c21c41ca18ab27fd4d5662920efd"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
