name = "MinePack Vanilla 2 Plus"
author = "yarinka-yyy"
version = "0.14.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "70dbe0d354f3e7fa17f05d182008e8da50883a8ec34bbdd083f120b2977284c2"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
