name = "MinePack Test Pack"
author = "yarinka-yyy"
version = "0.6.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7ec6cc63ac7ca7dfea1ebb82e2c743ea0dcd36bd408a424275e33c981d84d761"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
