name = "MinePack Test Pack"
author = "yarinka-yyy"
version = "0.18.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf1156124cbcf38d9679cdc7d0e389459d6594945a85c020c0398429a950106"

[versions]
fabric = "0.19.5"
minecraft = "26.2"
